version: "3"

services:
  tests:
    platform: linux/amd64
    image: maven:3.8.7-ibmjava-8
    container_name: tests
    working_dir: /tests
    volumes:
      - ./src:/tests/src
      - ./pom.xml:/tests/pom.xml
    network_mode: host
    command: mvn clean test